import { Box, Button, Card, CardActions, CardContent, Container, Divider, IconButton, Stack, Typography } from "@mui/material";
import ClauseCard from "../components/clause_card";
import AnalysisCard from "../components/analysis_card";
import copy from "../copy/copy.json"
import example_clauses from "../copy/example_clauses.json"
import React from "react";

export default function AnalysisPage() {

  const [level, setLevel] = React.useState(0);
  const [explanation, setExplanation] = React.useState("");
  
  const onPromptSend = async () => {
    console.log("Calling OpenAI...");
    //response api call...
    const response = await callGetResponse();
    setLevel(response.level)
    setExplanation(response.explanation)
    // console.log("Choice", response.result);
  }

  const body = {
    art: "7.1",
    clauses: example_clauses
  }

  const callGetResponse = async () => {
    //make api request
    const response = await fetch("/api", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });

    //process response
    const data = await response.json();
    return data;
  };

  const Submit = (event: React.MouseEvent<HTMLElement>) => {
      event.preventDefault();
      onPromptSend();
  };

  let clause_cards = example_clauses.map(function(clause) {
      return <ClauseCard
              title={clause.title}
              content={clause.content}
            /> 
  });

  const explaination = "This will be where the explaination generated by GPT4 will appear."


  return (
    <Container maxWidth={false}>
      <Stack
        direction="row"
        divider={<Divider orientation="vertical" flexItem />}
        spacing={2}
      >
        <Box sx={{ flexGrow: 0, flexShrink: 1, flexBasis: "auto" }} maxWidth={"50%"}>
          <Typography variant="h4" gutterBottom>
            Selected Clauses
          </Typography>
          <Stack spacing={1}>
            {clause_cards} 
          </Stack>
        </Box>
        <Box sx={{ flexGrow: 0, flexShrink: 1, flexBasis: "auto" }} maxWidth={"50%"}>
          <Typography variant="h4" gutterBottom>
            Analysis
          </Typography>
          <Stack spacing={1} >
            <AnalysisCard
              art_info={copy["7.1"]}
              explaination={explanation}
              level={level}
            />
            <AnalysisCard
              art_info={copy["7.2"]}
              explaination={explaination}
              level={0}
            />
            <AnalysisCard
              art_info={copy["7.3"]}
              explaination={explaination}
              level={0}
            />
            <AnalysisCard
              art_info={copy["7.4"]}
              explaination={explaination}
              level={0}
            />
          </Stack>
        </Box>
      </Stack>
      <Box sx={{ m: 2 }}>
        <Button variant="contained"
          onClick={Submit}
        >
          Submit 
        </Button>
      </Box> 
    </Container>
  );
}